version: '3.7'
services: 
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=somepassword
            - MYSQL_DATABASE=somedb
            - MYSQL_USER=user
            - MYSQL_PASSWORD=mysql
volumes: 
    db_data:
